### ISSUE TITLE
OpenSSL fork

### ISSUE THREAD

**Issue by paulcarroty** [UnitedRPMs/tribler#2]
## In the sequel of #1

@sergiomb2 proposed [the openssl fork](https://github.com/UnitedRPMs/openssl/releases/tag/1.0.2j-2) 'cause without it we have #1.

I think we can't overwrite the Fedora package because:
-  this is openssl, not a codec
-  tomorrow we'll must answer "why??" not only one time (@kuboosoft should remember gstreamer)
- we'll potentially lost our reputation

@sergiomb2 @kuboosoft your minds?

Looks like a rename for something like `openssl-elliptic` will be a best decision.

**Comment by sergiomb2** [comment]
my openssl , have bump epoch , is the same of fedora proper but with all ecliptic curves enabled. 
So will obsolete fedora proper openssl . I update the package with last updates off Fedora 25 ... , I use same patches, configurations etc, so end user don't have any missing feature .

**Comment by paulcarroty** [comment]
It's may be a politic decision, not technical. I don't see any tech problems here.

Let's democracy works - my vote for the <s>Hillary</s> rename. @kuboosoft?

**Comment by kuboosoft** [comment]
:) no problem

**Comment by paulcarroty** [comment]
@kuboosoft @sergiomb2 tribler with Sergio's openssl-full today will be added to repo, I need your help with testing.

**Comment by kuboosoft** [comment]
@paulcarroty @sergiomb2 I changed to openssl again... why is necessary openssl-freeworld here? I am testing the new release and download fine, but the anonimity doesn't work for me? I am not sure what is wrong; Is the first time I using tribler...

**Comment by sergiomb2** [comment]
hum don't you got errors like  ?
```
assert m2.ec_key_type_check(ec), "'ec' type error"
ValueError: Received a NULL pointer.
```

**Comment by kuboosoft** [comment]
@sergiomb2 https://github.com/UnitedRPMs/tribler/releases/tag/7.0.0-1.b

```
WARNING:SearchCommunity:message from <Candidate XXX.70.XX.237:XXXX> cannot be found in the request cache, skipping it
WARNING:TunnelLogger:Received message for unknown circuit ID: XX32389086
WARNING:SearchCommunity:message from {XXX.16X.1.100:XX XX.213.2X.150:XX} cannot be found in the request cache, skipping it
WARNING:Timeline:FAIL time:5 user:691xx -> permit^channel (no authorization)
```

All trackers is "not working" in mode anon...

**Comment by sergiomb2** [comment]
about #Requires: python-libnacl  , python-libnacl  is available now on Fedora
https://admin.fedoraproject.org/pkgdb/package/rpms/python-libnacl/

**Comment by kuboosoft** [comment]
@sergiomb2 you can enable the dependency :smile:
